creeper: true
Line0: command
invalidline1: Fehler
invalidline2: Fehler
invalidline3: Fehler
invalidLinePlayer: Fehler
MissingPermissonUse: Fehler
MissingPermCrPl: Fehler
MissingPermnDelPl: Fehler
MisPermCrLi1: Fehler
MisPermCrLi2: Fehler
MisPermCrLi3: Fehler
MisPermCrLi4: Fehler
SetLine0Command: command
mwssigncreate: mws.sign.create
mwssignuse: mws.sign.use
mwssigndel: mws.sign.del
title-name: '&a[MWS SIGNS]:&f'
MWS: MultiWorldSystem
Perms: mws.sign.use

GraveLine0: §e------R.I.P------
GraveLine1: mwsrepair
GraveLine2: 
GraveLine3: §e-----------------

PlayerBankSaveMessageTitel: MultiWorldSystem Saved
PlayerBankSaveMesssageTitel2: his bank
VipBankSaveMessageTitel: MultiWorldSystem Saved
VipBankSaveMesssageTitel2: his VIP bank
BankName: MultiWorldSystem ITEM Bank
PlayerImmuneInBank: true
Plevel: 1
Pupgrade_price: 500
Slots: 54
VipBankName: MultiWorldSystem VIP ITEM Bank
PlayerImmuneInVipBank: true
Vlevel: 1
Vupgrade_price: 500
VipSlots: 54

shopseterror1: Shop successfully set.
shopplno: have not a shop.
shopuse: Use /mwsshop <player>
shopremoved: Shop deleted from config.

shopLine1: PlayersShop
shopvisit: v
shopbuy: b
shopsell: s

shops: {}