#default config
# This plugin has integrated the shop year 2013 from [Blc_Dragon] https://repos.bukkit.org/minecraft/guishop guishop
#name of language file, you can use de_DE,en_US,ru_RU. After change reload the server, thats do the lang file in the folder from plugin
useVault: true
JoinKit: true
lang: 'de_DE'
#prefix of your shop menu
UseTabPrefix: true
TabPrefix: '&8[&eMWS Shop]'
#prefix setups
UseMessagePrefix: true
Prefix: '&8[&eMWS Shop]'
Tent: Tent
BasicHouse: Basic House
HouseSpongeBob: House Sponge bob
#gamerules
doDaylightCycle: true
doDaylightCycleText: set DaylightCycle for 
doEntityDrops: true
doEntityDropsText: set EntityDrops for
doMobLoot: true
doMobLootText: set MobLoot for
doMobSpawning: true
doMobSpawningText: set MobSpawning for

doTileDrops: true
doTileDropsText: set TileDrops for
doWeatherCycle: true
doWeatherCycleText: set WeatherCycle for
doLimitedCrafting: true
doLimitedCraftingText: set LimitedCrafting for
doFireTick: true
doFireTickText: set FireTick for
ElytraMovementCheck: true
ElytraMovementCheckText: enable ElytraMovementCheck for
docommandBlockOutput: true
docommandBlockOutputText: set BlockOutput for
doannounceAdvancements: true
doannounceAdvancementsText: set Advancements for
#Logging
LogInfo: true
LogFileName: log
LogToConsole: false
checkForUpdates: true
creeper: true
thunder: true
notify_update_available: true
Line0: command
invalidline1: Fehler
invalidline2: Fehler
invalidline3: Fehler
invalidLinePlayer: Fehler
MissingPermissonUse: Fehler
MissingPermCrPl: Fehler
MissingPermnDelPl: Fehler
MisPermCrLi1: Fehler
MisPermCrLi2: Fehler
MisPermCrLi3: Fehler
MisPermCrLi4: Fehler
SetLine0Command: command
mwssigncreate: mws.sign.create
mwssignuse: mws.sign.use
mwssigndel: mws.sign.del
title-name: '&a[MWS SIGNS]:&f'
MWS: MultiWorldSystem
Perms: mws.sign.use
#if you do commands on gravesign, please only 0 line Rip Name and 1 line command. 2 and 3 let it empty!
GraveLine0: §e------R.I.P------
GraveLine1: 
GraveLine2: 
GraveLine3: §e-----------------

PlayerBankSaveMessageTitel: MultiWorldSystem Saved
PlayerBankSaveMesssageTitel2: his bank
VipBankSaveMessageTitel: MultiWorldSystem Saved
VipBankSaveMesssageTitel2: his VIP bank

BankName: MultiWorldSystem ITEM Bank
PlayerImmuneInBank: true
Plevel: 1
Pupgrade_price: 500
Slots: 54
VipBankName: MultiWorldSystem VIP ITEM Bank
PlayerImmuneInVipBank: true
Vlevel: 1
VipSlots: 54
PlayerShopName: MultiWorldSystem BUY ITEM CHEST
PlayerImmuneInShop2: true
PlayerShopName: Buy Chest
Shop2Slots: 54


GuiName: "MultiWorldSystem Menu"
Guipermission: mws.gui.use
GuiRows: 6

GuiOpeningCommand: "mwsgui"
Items:
  Home Teleport:
    ItemID: 12
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 0
    ItemAmmount: 1
    Description: '&7Home'
    Commands:
    - home
  Home Set:
    ItemID: 1
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 1
    ItemAmmount: 1
    Description: '&7set Home'
    Commands:
    - shome
  Gamemode 1:
    ItemID: 12
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 2
    ItemAmmount: 1
    Description: '&7Set Creative Gamemode'
    Commands:
    - g1
  Gamemode 0:
    ItemID: 12
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 3
    ItemAmmount: 1
    Description: '&7Survival Gamemode'
    Commands:
    - g0
  Player Bank:
    ItemID: 1
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 4
    ItemAmmount: 1
    Description: '&7Player Bank'
    Commands:
    - bankopen
  Vip Bank:
    ItemID: 1
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 5
    ItemAmmount: 1
    Description: '&7Vip Bank'
    Commands:
    - vipbank
  Set Hub:
    ItemID: 1
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 6
    ItemAmmount: 1
    Description: '&7Set Hub'
    Commands:
    - shub
  Weather clear:
    ItemID: 60
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 7
    ItemAmmount: 1
    Description: '&7Weather Clear'
    Commands:
    - wclear
  hub tp:
    ItemID: 1
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 8
    ItemAmmount: 1
    Description: '&7tp to hub'
    Commands:
    - hub
  Creeper on:
    ItemID: 60
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 9
    ItemAmmount: 1
    Description: '&7Creeper Dmg on'
    Commands:
    - creeper false
  Creeper off:
    ItemID: 60
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 10
    ItemAmmount: 1
    Description: '&7Creeper Dmg off'
    Commands:
    - creeper true
  Heal:
    ItemID: 60
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 11
    ItemAmmount: 1
    Description: '&7heal'
    Commands:
    - heal
  Repair:
    ItemID: 60
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 12
    ItemAmmount: 1
    Description: '&7Creeper Dmg on'
    Commands:
    - mwsrepair
  Flymode:
    ItemID: 60
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 13
    ItemAmmount: 1
    Description: '&7Fly on & off'
    Commands:
    - f
  Flyspeed:
    ItemID: 60
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 14
    ItemAmmount: 1
    Description: '&7flyspeed double'
    Commands:
    - fs 50  
  FlyspeedStandard:
    ItemID: 60
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 15
    ItemAmmount: 1
    Description: '&7flyspeed'
    Commands:
    - fs 20      
  Walkpeed:
    ItemID: 60
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 16
    ItemAmmount: 1
    Description: '&7walkspeed double'
    Commands:
    - walk 50
  Day:
    ItemID: 60
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 17
    ItemAmmount: 1
    Description: '&7set Day'
    Commands:
    - day
  Kill all Mobs:
    ItemID: 60
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 18
    ItemAmmount: 1
    Description: '&7killmobs'
    Commands:
    - killmob
  nightvision:
    ItemID: 1
    ItemDataValue: 0
    ItemDamage: 0
    ItemSlot: 19
    ItemAmmount: 1
    Description: '&7Nightvision'
    Commands:
    - nightvision
                          

shopseterror1: Shop successfully set.
shopplno: have not a shop.
shopuse: Use /mwsshop <player>
shopremoved: Shop deleted from config.

shopLine1: PlayersShop
shopvisit: v
shopbuy: b
shopsell: s

shops: {}